name: newman_report

on: push

jobs:
  automated-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: |
          mkdir -p testResults

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run tests
        run: |
          newman run "LearingRESTFULService.json" -r html --reporter-html-export testResults/index.html

      - name: Output the results
        uses: actions/upload-artifact@v3
        with:
          name: RunReporter
          path: testResults

      - name: Test marketplace action
        uses: PavanMudigonda/html-reporter-github-pages@v1.0
        id: test-report
        with:
          test_results: testResults
          gh_pages: gh-pages
          results_history: results-history

      - name: Publish Github Pages
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: results-history
          keep_files: true 

          environment: 5922408-228c7edd-fc15-4f68-9665-a35d7df6945b

